#!/usr/bin/env ruby

require './tool/LocalConfig.rb'

archDir = LocalConfig::getExecPlatform().to_s

topDir = File.dirname(File.expand_path(__FILE__))
srcDir = "#{topDir}/extlib/build/"
dstDir = "#{topDir}/build/"

print "copying libraries..."
system("mkdir -p #{dstDir}/lib/#{archDir}/")
system("cp -a #{srcDir}/lib/*     #{dstDir}/lib/#{archDir}/")
system("cp -r #{srcDir}/include/  #{dstDir}")
puts "done"
